export const chatAction = {
    changeActivePerson: '[chat] change active person',
    deleteConversationItem: '[chat] delete conversation item',
    receiveSingleMessage: '[chat] receive single message',
    receiveGroupMessage: '[chat] receive group message',
    receiveMessageSuccess: '[chat] receive message success',
    sendSinglePic: '[chat] send single picture',
    sendGroupPic: '[chat] send group pic',
    sendSingleFile: '[chat send single file',
    sendGroupFile: 'send group file',
    sendSingleMessage: '[chat] send single message',
    sendGroupMessage: '[chat] send group message',
    sendMsgComplete: 'send message complete',
    getConversation: '[chat] get conversation',
    getConversationSuccess: '[chat] get conversation success',
    getAllMessage: '[chat] get all message',
    getAllMessageSuccess: '[chat] get all message success',
    saveDraft: '[chat] save draft',
    watchOtherInfo: '[chat] watch other info',
    watchOtherInfoSuccess: '[chat] watch other info success',
    hideOtherInfo: '[chat] hide other info',
    groupSetting: '[chat] group setting',
    groupInfo: '[chat] group info',
    searchUserSuccess: '[chat] search user success',
    getSourceUrl: '[chat] get source url',
    dispatchConversationList: '[chat] dispatch conversation list',
    groupDescription: '[chat] group description',
    groupName: '[chat] group name',
    updateGroupInfo: '[chat] update group info',
    getMemberAvatarUrl: '[chat] get member avatar url',
    getSingleAvatarUrl: '[chat] get single avatar url',
    changeGroupShield: '[chat] change shield',
    changeGroupShieldSuccess: '[chat] change shield success',
    changeGroupNoDisturb: '[chat] change no disturb',
    changeGroupNoDisturbSuccess: '[chat] change no disturb success',
    createOtherChat: '[chat] create other chat',
    addGroupMembersEvent: '[chat] add group members event',
    addGroupMembersEventSuccess: '[chat] add group members event success',
    getVoiceState: '[chat] get voice state',
    getVoiceStateSuccess: '[chat] get voice state success',
    playVideoShow: '[chat] play video show',
    updateContactInfo: '[chat] update contact info',
    updateGroupMembersEvent: '[chat] update group members',
    deleteGroupMembersEvent: '[chat] delete group members event',
    exitGroupEvent: '[chat] exit group event',
    createGroupEvent: '[chat] create group event',
    createGroupSuccessEvent: '[chat] create group success event',
    friendInvitationEvent: '[chat] friend invitation event',
    friendReplyEvent: '[chat] friend reply event',
    init: '[chat] init state',
    msgRetract: '[chat] message retract',
    msgRetractSuccess: '[chat] message retract success',
    msgRetractEvent: '[chat] message retract event',
    msgTransmit: '[chat] message transmit',
    msgTransmitSuccess: '[chat] message transmit success',
    searchMessageTransmit: '[chat] search message transmit',
    transmitSingleMessage: '[chat] transmit single message',
    transmitGroupMessage: '[chat] transmit group message',
    transmitSinglePic: '[chat] transmit single picture',
    transmitGroupPic: '[chat] transmit group picture',
    transmitSingleFile: '[chat] transmit single file',
    transmitGroupFile: '[chat] transmit group file',
    transmitSingleLocation: '[chat] transmit single location',
    transmitGroupLocation: '[chat] transmit group location',
    transmitMessageComplete: '[chat] transmit message complete',
    showVerifyModal: '[chat] show verify modal',
    addFriendConfirm: '[chat] add friend confirm',
    deleteSingleBlack: '[chat] delete single black',
    deleteSingleBlackSuccess: '[chat] delete single black success',
    deleteSingleNoDisturb: '[chat] delete single no disturb',
    deleteSingleNoDisturbSuccess: '[chat] delete single no disturb success',
    saveMemoName: '[chat] save memo name',
    saveMemoNameSuccess: '[chat] save memo name success',
    dispatchFriendList: '[chat] dispatch friend list',
    loadViewerImage: '[chat] load viewer image',
    loadViewerImageSuccess: '[chat] load viewer image success',
    getGroupMembers: '[chat] get group members',
    msgFile: '[chat] msg file',
    msgFileSuccess: '[chat] msg file success',
    dispatchMessageUnread: '[chat] dispatch message unread',
    fileImageLoad: '[chat] file image load',
    groupAvatar: '[chat] group avatar',
    conversationToTop: '[chat] conversation to top',
    conversationToTopSuccess: '[chat] conversation to top success',
    watchUnreadList: '[chat] watch unread list',
    watchUnreadListSuccess: '[chat] watch unread list success',
    addReceiptReportAction: '[chat] add receipt report action',
    addReceiptReport: '[chat] add receipt report',
    msgReceiptChangeEvent: '[chat] msg receipt change event'
};
