export const chatAction = {
    changeActivePerson: '[chat] change active person',
    deleteConversationItem: '[chat] delete conversation item',
    receiveMessage: '[chat] receive message',
    receiveMessageSuccess: '[chat] receive message success',
    sendSinglePic: '[chat] send single picture',
    sendGroupPic: '[chat] send group pic',
    sendSingleFile: '[chat send single file',
    sendGroupFile: 'send group file',
    sendSingleMessage: '[chat] send single message',
    sendGroupMessage: '[chat] send group message',
    sendMsgComplete: 'send message complete',
    getConversation: '[chat] get conversation',
    getConversationSuccess: '[chat] get conversation success',
    getAllMessage: '[chat] get all message',
    getAllMessageSuccess: '[chat] get all message success',
    saveDraft: '[chat] save draft',
    watchOtherInfo: '[chat] watch other info',
    watchOtherInfoSuccess: '[chat] watch other info success',
    hideOtherInfo: '[chat] hide other info',
    groupSetting: '[chat] group setting',
    groupInfo: '[chat] group info',
    searchUserSuccess: '[chat] search user success',
    getSourceUrl: '[chat] get source url',
    dispatchConversationList: '[chat] dispatch conversation list',
    groupDescription: '[chat] group description',
    groupName: '[chat] group name',
    updateGroupInfo: '[chat] update group info',
    getMemberAvatarUrl: '[chat] get member avatar url',
    getSingleAvatarUrl: '[chat] get single avatar url',
    changeGroupShield: '[chat] change no disturb',
    changeGroupShieldSuccess: '[chat] change no disturb success',
    createOtherChat: '[chat] create other chat',
    addGroupMembersEvent: '[chat] add group members event',
    addGroupMembersEventSuccess: '[chat] add group members event success',
    getVoiceState: '[chat] get voice state',
    getVoiceStateSuccess: '[chat] get voice state success',
    playVideoShow: '[chat] play video show',
    updateContactInfo: '[chat] update contact info',
    updateGroupMembersEvent: '[chat] update group members',
    deleteGroupMembersEvent: '[chat] delete group members event',
    exitGroupEvent: '[chat] exit group event',
    createGroupEvent: '[chat] create group event',
    createGroupSuccessEvent: '[chat] create group success event',
    init: '[chat] init state'
};
