export const roomAction = {
    getRoomList: '[room] get room list',
    getRoomListSuccess: '[room] get room list success',
    changeRoom: '[room] change room',
    changeRoomSuccess: '[room] change room success',
    enterRoom: '[room] enter room',
    enterRoomSuccess: '[room] enter room success',
    enterRoomError: '[room] enter room success error',
    exitRoom: '[room] exit room',
    exitRoomSuccess: '[room] exit room success',
    showRoomInfomation: '[room] show room infomation',
    showRoomInfomationSuccess: '[room] show room infomation success',
    receiveMessage: '[room] receive message',
    receiveMessageSuccess: '[room] receive message success',
    receiveMessageUrlSuccess: '[room] receive message url success',
    getSelfChatrooms: '[room] get self chatrooms',
    exitAllChatroomsSuccess: '[room] get all chatrooms success',
    sendTextMsg: '[room] send text msg',
    transmitPicMsg: '[room] transmit pic msg',
    sendFileMsg: '[room] send file msg',
    sendPicMsg: '[room] send pic msg',
    sendMsgComplete: '[room] send msg complete',
    transmitAllMsg: '[room] transmit all msg',
    getRoomVoiceState: '[room] get room voice state',
    getRoomVoiceStateSuccess: '[room] get room voice state success',
    showPanel: '[room] show panel'
};
