export const mainAction = {
    getSelfInfo: '[main] get self info',
    showSelfInfo: '[main] show self info',
    updateSelfInfo: '[main] update self info',
    updateSelfInfoFlag: '[main] update self info flag',
    changeListTab: '[main] change list tab',
    logoutAction: '[main] logout action',
    createGroupShow: '[main] create group show',
    createGroup: '[main] create group',
    addGroupMember: '[main] add group member',
    addGroupMemberSuccess: '[main] add group member success',
    createGroupSuccess: '[main] create group success',
    modifyPasswordShow: '[main] modify password show',
    modifyPassword: '[main] modify password',
    searchUser: '[main] search user',
    searchUserSuccess: '[main] search user success',
    selectSearchUser: '[main] select search user',
    selectSearchRoomUser: '[main] select search room user',
    hideModalTip: '[main] hide modal tip',
    showModalTip: '[main] show modal tip',
    addBlackListAction: '[main] add black list action',
    addBlackListSuccess: '[main] add black list success',
    createSingleChatShow: '[main] create single chat show',
    createSingleChatAction: '[main] create single chat action',
    createSingleChatSuccess: '[main] create single chat success',
    emptySingleChatTip: '[main] empty single chat tip',
    blackMenu: '[main] black menu',
    blackMenuSuccess: '[main] black menu success',
    delSingleBlack: '[main] delete single black',
    delSingleBlackSuccess: '[main] delete single black success',
    hideBlackMenu: '[main] hide black menu',
    selectGroupItem: '[main] select group item',
    exitGroupAction: '[main] exit group action',
    exitGroupSuccess: '[main] exit group success',
    deleteMemberAction: '[main] delete member action',
    deleteMemberSuccess: '[main] delete member success',
    createGroupSearchAction: '[main] create group search action',
    login: '[main] login',
    logoutKickShow: '[main] logout kick show',
    init: '[main] init',
    addSingleNoDisturbAction: '[main] add single no disturb action',
    addSingleNoDisturbSuccess: '[main] add single no disturb success',
    deleteFriend: '[main] delete friend',
    deleteFriendSuccess: '[main] delete friend success',
    dispatchSendSelfCard: '[main] dispatch send self card',
    enterPublicGroupShow: '[main] enter public group show',
    searchPublicGroup: '[main] search public group',
    searchPublicGroupSuccess: '[main] search public group success',
    groupVerifyModal: '[main] group verify modal',
    sendGroupVerifyMessage: '[main] send group verify message',
    createGroupNextShow: '[main] create group next show',
    // 确认提示模态框action
    logoutShowConfirmModal: '[main] logout show confirm modal',
    addBlackListConfirmModal: '[main] add black list confirm modal',
    exitGroupConfirmModal: '[main] exit group confirm modal',
    deleteMemberConfirmModal: '[main] delete member',
    addSingleNoDisturbConfirmModal: '[main] add single no disturb confirm modal',
    deleteFriendConfirmModal: '[main] delete friend modal'
};
